# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish on NPM

on:
  push:
    branches: ['master']
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g @vscode/vsce
      - uses: actions/setup-node@v3
      - run: vsce publish
        env:
          VSCE_PAT: ${{secrets.VSCE_PAT}}
